import { ClientLayout } from '@/layouts/ClientLayout';
import clsx from 'clsx';
import type { Metadata, Viewport } from 'next';
import { Montserrat } from 'next/font/google';
import './globals.css';

const montserrat = Montserrat({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={clsx(
          montserrat.className,
          'min-h-dvh max-w-screen-sm mx-auto py-10 px-4'
        )}
      >
        <h1 className='text-2xl font-bold text-secondary'>overreacted</h1>
        <ClientLayout>{children}</ClientLayout>
      </body>
    </html>
  );
}
